# Position of Energy, Stamina and Resolve bars in the HUD.
#Allowed Values: TOP_LEFT, TOP_RIGHT, LEFT, RIGHT
barsPosition = "TOP_LEFT"
# Position of Power name, Attack and Ability hotbars in the HUD.
#Allowed Values: TOP_LEFT, TOP_RIGHT, LEFT, RIGHT
hotbarsPosition = "TOP_LEFT"
# How Power, Attack and Ability names should render in the HUD.
#Allowed Values: ALWAYS, FADE_AWAY, NEVER
hudNamesRender = "ALWAYS"
# Enable hotkey settings for each individual attack and ability from 1 to 9.
#  If your client is launched, changing the setting requires restarting the game.
actionSlotHotkeys = false
# Enable shaders during Resolve effect.
resolveShaders = true
# Enable particles spawning from the player when AFK.
menacingParticles = true
# Freeze particles, block texture animations and rain/snow during time stop.
#  Experimental feature - it may cause errors or crashes with other mods (one known crash is with Dynamic Surroundings), so the option is disabled by default.
timeStopFreezesParticles = false
# Enables the visual effect at the beginning of time stop when its duration is 5 seconds or longer.
timeStopAnimation = true
# Whether or not voice lines of the JoJo characters whose powers the players use are played.
characterVoiceLines = true

